version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "$REDIS_PORT:6379"
    command: redis-server --port 6379 --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
