version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .docker.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .docker.env
    ports:
      - "$REDIS_PORT:6379"
    command: redis-server --port 6379 --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .docker.env

  notifier:
    build: .
    command: python3 -m src.presentation.notifier.main
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .docker.env