"""User & Applicant

Revision ID: 27b909e218bb
Revises: 
Create Date: 2024-10-18 22:07:49.129300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b909e218bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('role', sa.Enum('recruiter', 'APPLICANT', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_applicants',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_title', sa.String(length=256), nullable=True),
    sa.Column('job_salary', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_applicants.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_experiences_user_id'), 'experiences', ['user_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_applicants.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_skills_user_id'), 'skills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_user_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_experiences_user_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_table('user_applicants')
    op.drop_table('users')
    # ### end Alembic commands ###
