"""applications (zayavki)

Revision ID: e0bf62d61415
Revises: b618517184c0
Create Date: 2024-10-19 13:01:41.944051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bf62d61415'
down_revision: Union[str, None] = 'b618517184c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'REJECTED', 'INVITED', 'ACCEPTED', name='applicationstatus'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['user_applicants.user_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_applications_applicant_id'), 'applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_unique_constraint(None, 'experiences', ['id'])
    op.create_unique_constraint(None, 'jobs', ['id'])
    op.create_unique_constraint(None, 'skills', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_constraint(None, 'experiences', type_='unique')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applicant_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
